-- MySQL Script generated by MySQL Workbench
-- Wed Oct 25 00:36:46 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema user
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema user
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `user` DEFAULT CHARACTER SET utf8 ;
USE `user` ;

-- -----------------------------------------------------
-- Table `user`.`user_info`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `user`.`user_info` (
  `user_id` INT NOT NULL,
  `first_name` VARCHAR(20) NULL,
  `last_name` VARCHAR(20) NULL,
  `age` INT NULL,
  `gender` VARCHAR(5) NULL,
  `email` VARCHAR(45) NULL,
  `is_admin` TINYINT(1) NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `user`.`user_login`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `user`.`user_login` (
  `user_info_user_id` INT NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `password_hash` BINARY NULL,
  `salt` BINARY NULL,
  `last_login_time` TIMESTAMP NULL,
  `login_attempts` INT NULL,
  `creation_time` DATE NULL,
  `last_update_time` DATE NULL,
  `session_token` VARCHAR(60) NULL,
  UNIQUE INDEX `email_addr_UNIQUE` (`username` ASC) VISIBLE,
  UNIQUE INDEX `user_name_UNIQUE` (`last_login_time` ASC) VISIBLE,
  PRIMARY KEY (`username`),
  INDEX `fk_user_login_user_info_idx` (`user_info_user_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_login_user_info`
    FOREIGN KEY (`user_info_user_id`)
    REFERENCES `user`.`user_info` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
