# This is a basic workflow that is manually triggered

name: Testing workflow.

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  cypressTesting:
    runs-on: ubuntu-latest
    steps:
      - name: Cypress.io
        uses: cypress-io/github-action@v6.6.0
        with:
          build: npm run build
          start: npm start
          browser: chrome
          working-directory: ./src
        
